// Action Types
export const LOAD_PLANETS_SUCCESS = 'LOAD_PLANETS_SUCCESS'
export const LOAD_PLANET_SUCCESS = 'LOAD_PLANET_SUCCESS'
export const LOAD_PLANETS_SEARCH_SUCCESS = 'LOAD_PLANETS_SEARCH_SUCCESS'

export const LOAD_SPACESHIPS_SUCCESS = 'LOAD_SPACESHIPS_SUCCESS'
export const LOAD_SPACESHIP_SUCCESS = 'LOAD_SPACESHIP_SUCCESS'
export const LOAD_SPACESHIPS_SEARCH_SUCCESS = 'LOAD_SPACESHIPS_SEARCH_SUCCESS'

export const LOAD_VEHICLES_SUCCESS = 'LOAD_VEHICLES_SUCCESS'
export const LOAD_VEHICLE_SUCCESS = 'LOAD_VEHICLE_SUCCESS'
export const LOAD_VEHICLES_SEARCH_SUCCESS = 'LOAD_VEHICLES_SEARCH_SUCCESS'

export const LOAD_PEOPLE_SUCCESS = 'LOAD_PEOPLE_SUCCESS'
export const LOAD_PERSON_SUCCESS = 'LOAD_PERSON_SUCCESS'
export const LOAD_PEOPLE_SEARCH_SUCCESS = 'LOAD_PEOPLE_SEARCH_SUCCESS'

export const LOAD_FILMS_SUCCESS = 'LOAD_FILMS_SUCCESS'
export const LOAD_FILM_SUCCESS = 'LOAD_FILM_SUCCESS'
export const LOAD_FILMS_SEARCH_SUCCESS = 'LOAD_FILMS_SEARCH_SUCCESS'
export const LOAD_FILM_WOOKIEE_SUCCESS = 'LOAD_FILM_WOOKIEE_SUCCESS'

export const LOAD_SPECIES_SUCCESS = 'LOAD_SPECIES_SUCCESS'
export const LOAD_SINGLE_SPECIES_SUCCESS = 'LOAD_SINGLE_SPECIES_SUCCESS'
export const LOAD_SPECIES_SEARCH_SUCCESS = 'LOAD_SPECIES_SEARCH_SUCCESS'

export const REQUEST_STARTED = 'REQUEST_STARTED'
export const REQUEST_FINISHED = 'REQUEST_FINISHED'
export const REQUEST_FAILED = 'REQUEST_FAILED'

export const SET_WOOKIEE = 'SET_WOOKIEE'
