export const personData = {
  name: '',
  height: '',
  mass: '',
  hair_color: '',
  skin_color: '',
  eye_color: '',
  birth_year: '',
  gender: '',
  homeworld: '',
  species: [],
  vehicles: [],
  starships: [],
  films: [],
  created: '',
  edited: '',
  url: '',
}
