export const speciesData = {
  name: '',
  classification: '',
  designation: '',
  average_height: '',
  skin_colors: '',
  hair_colors: '',
  eye_colors: '',
  average_lifespan: '',
  homeworld: '',
  language: '',
  people: [],
  films: [],
  created: '',
  edited: '',
  url: '',
}
