export const vehicleData = {
  name: '',
  model: '',
  manufacturer: '',
  cost_in_credits: '',
  length: '',
  max_atmosphering_speed: '',
  crew: '',
  passengers: '',
  cargo_capacity: '',
  consumables: '',
  vehicle_class: '',
  pilots: [],
  films: [],
  created: '',
  edited: '',
  url: '',
}
